<?php

class tab_setari_topbanners extends tab {
	public  $show_sidebar             = false;					/* will display right sidebar info (only if $this->edit_tab==true ) */
	public  $label_size               = 2;
	public  $sidebar_width            = 4;						/* no between 2 and 10 */			
	/* ------------------------------------------------------------------------------------- */	
	public  $show_line_between_fields = false;
	public $fields = 
		array( 
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - IMPLICIT',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_default',
				  'input_type'                         => 'tb_default',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_default',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => true,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit al site-ului',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_default_opacity',
                  'db_field'                           => 'tb_default_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului implicit',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top implicit',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - GALERIE FOTO',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_image_gallery',
				  'input_type'                         => 'tb_image_gallery',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_image_gallery',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_image_gallery_opacity',
                  'db_field'                           => 'tb_image_gallery_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria foto',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei foto',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - GALERIE VIDEO',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_video_gallery',
				  'input_type'                         => 'tb_video_gallery',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_video_gallery',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_video_gallery_opacity',
                  'db_field'                           => 'tb_video_gallery_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - COLECTIA DE AFISE',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_afise',
				  'input_type'                         => 'tb_afise',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_afise',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_afise_opacity',
                  'db_field'                           => 'tb_afise_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
						  
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - EDITURA ISTROS',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_istros',
				  'input_type'                         => 'tb_istros',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_istros',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_istros_opacity',
                  'db_field'                           => 'tb_istros_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - PUBLICATII BRAILA',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_pub_braila',
				  'input_type'                         => 'tb_pub_braila',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_pub_braila',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_pub_braila_opacity',
                  'db_field'                           => 'tb_pub_braila_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - EVENIMENTE',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_events',
				  'input_type'                         => 'tb_events',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_events',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_events_opacity',
                  'db_field'                           => 'tb_events_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
                 array (
                  'type'                               => FIELD_TYPE_TITLE,
                  'title'                              => 'BANNER TOP - ANUNTURI',
                  'color_class'                        => 'font-green',                     /* Empty fo default */
                  'icon_class'                         => 'fa fa-gear',
                  'bold'                               => false,
                  ),
		
				array (
                  'type'                               => FIELD_TYPE_SELECT_FILE,
                  'title'                              => 'Banner top [1920 x 325]',
                  'control_name'                       => 'tb_ads',
				  'input_type'                         => 'tb_ads',
				  'unique'							   => false,
                  'control_id'                         => '',                  
                  'db_field'                           => 'tb_ads',
                  'value'                              => '', 
                  'maxlength'                          => '',
                  'read_only'                          => false,
                  'required'                           => false,
				  'show_preview'                       => true,
				  'auto_height'                        => true,
                  'required_message'                   => 'Introduceti banner-ul top implicit',
                  'placeholder'                        => '',
                  'pattern'                            => '',
			      'column_size'                        => '',
			      'width'                        	   => '',
		          'icon'                    		   =>  array(
	                                                             array (
	                                                              'class'              => 'fa fa-photo',
	                                                              'type'       	       => '1',
	                                                              'color'              => 'font-red',  			
	                                                             ),				  
															),
                       ),
                  array (
                  'type'                               => FIELD_TYPE_COMBO_BOOTSTRAP_CUSTOM,
                  'title'                              => 'Opacitate banner top',
                  'control_name'                       => 'tb_ads_opacity',
                  'db_field'                           => 'tb_ads_opacity',
                  'control_id'                         => '',                                    
                  'read_only'                          => false,
                  'required'                           => true,
                  'required_message'                   => 'Selectati opacitatea Top bannerului pentru galeria video',
                  'column_size'                        => '',
                  'width'                              => '',                                                                                               /* Can be: input-xlarge, input-large, input-medium, input-small, input-xsmall. Recomanded: use column_size instead this property */
				  'help_message'                       => 'Selectati gradul de opacitate al banner-ului top al galeriei video',
                  'attributes'                         => array(
                                                                   array ( 'value' =>  '0',  'selected' => false, 'title'   => '0.0', ),
																   array ( 'value' =>  '1',  'selected' => false, 'title'   => '0.1', ),
																   array ( 'value' =>  '2',  'selected' => false, 'title'   => '0.2', ),
																   array ( 'value' =>  '3',  'selected' => false, 'title'   => '0.3', ),
																   array ( 'value' =>  '4',  'selected' => false, 'title'   => '0.4', ),
																   array ( 'value' =>  '5',  'selected' => false, 'title'   => '0.5', ),
																   array ( 'value' =>  '6',  'selected' => false, 'title'   => '0.6', ),
																   array ( 'value' =>  '7',  'selected' => false, 'title'   => '0.7', ),
																   array ( 'value' =>  '8',  'selected' => false, 'title'   => '0.8', ),
																   array ( 'value' =>  '9',  'selected' => false, 'title'   => '0.9', ),
                                                               ),
                        ),
					   

	    );
	/* ------------------------------------------------------------------------------------- */	
	public function __construct() {
		parent::__construct();		

	}	
	/* ------------------------------------------------------------------------------------- */	
}